version: "3.7"

networks:
  app-tier:
    driver: bridge

services:
  database:
    image: postgres
    container_name: database_fin_comp
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - app-tier
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=finctrl
      - POSTGRES_DB=fin_ctrl
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: fin_ctrl_comp
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    networks:
      - app-tier

volumes:
  pgdata:
    driver: local