version: "3.1"

services:
  db:
    image: postgres
    container_name: fin_ctrl_db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: finctrl
      POSTGRES_DB: fin_ctrl
    ports:
      - 5432:5432